<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>60a0be66-3bf4-4244-aa0f-0cbebe3349dd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedRef.Shared\MedRef.Shared.csproj" />
  </ItemGroup>

</Project>
